events {}

http {

  # HTTP → HTTPS
  server {
    listen 80;
    return 301 https://$host$request_uri;
  }

  # HTTPS (внутрішній)
  server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    # Grafana
    location / {
      proxy_pass http://grafana:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Prometheus
    location /prometheus/ {
      proxy_pass http://prometheus:9090/;
    }

    # MinIO
    location /minio/ {
      proxy_pass http://minio:9001/;
    }
  }
}
